stages:
  load_data:
    cmd:  python src/process_and_load.py --config=params.yaml
    deps:
    - src/get_param.py
    - data_given/adult.csv
    outs:
    - data/raw/adult.csv
  split:
    cmd: python src/split.py --config=params.yaml
    deps:
    - data/raw/adult.csv
    - src/split.py
    outs:
    - data/processed/train.csv
    - data/processed/test.csv
  eval:
    cmd: python src/model_train_evl.py --config=params.yaml
    deps:
    - data/processed/train.csv
    - data/processed/test.csv
    - src/model_train_evl.py
    params:
    - model.knn.params.n_neighbours
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/knnmodel.pkl
    - saved_models/ct.pkl

