name: python-application
on:
  push:
    branches:
      master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  
    - name: install dependency
      run: |
        python -m pip install --upgrade pip
        pip install -r recquirement.txt
    - name: deploy to heroku
      env:
        HEROKU_API_NAME: ${{secrets.HEROKU_API_NAME}}
        HEROKU_API_TOKEN: ${{secrets.HEROKU_API_TOKEN}}
      if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
        git push heroku HEAD:main -f
    